### ISSUE TITLE
Device not found

### ISSUE THREAD

**Issue by HonestyLied** [JarodMica/rvc-tts-pipeline#2]
i'm trying to get this working but when it goes to process using rcv i get this error: Cuda or MPS not detected
Exception in thread Thread-4:
Traceback (most recent call last):
  File "C:\Users\M\AppData\Local\Programs\Python\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Users\M\AppData\Local\Programs\Python\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\M\PycharmProjects\pythonProject2\tortrvc.py", line 549, in handle_message
    processed_audio_path = rvc_convert(model_path=model_path, input_path=original_audio_path)
  File "c:\users\m\pycharmprojects\pythonproject2\venv\src\rvc-tts-pipe\rvc_infer.py", line 330, in rvc_convert
    config=Config(device,is_half)
NameError: name 'device' is not defined

i'm new to coding so sorry if the issue is obvious

**Comment by HonestyLied** [comment]
did a fresh install and changed these lines is rvc_convert: if torch.cuda.is_available():
    device = "cuda:0"
elif torch.backends.mps.is_available():
    device = "mps:0"
else:
    print("Cuda or MPS not detected") 

to: device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

and that seems to have fixed it

**Comment by HonestyLied** [comment]
also had an issue with the half parameter

changing this line: self.is_half = True
to: self.is_half = False

which fixed the issue

**Comment by JarodMica** [comment]
Are you running it with an Nvidia GPU? The issues your running into is due to the script running on CPU as I didn't code the alternative logic needed for it.

I'll have to add this as an enhancement to the original logic in case people wanna run the pipeline using CPU inference.

**Comment by HonestyLied** [comment]
ah yup that's exactly why, im trying to run it on gpu, thanks for clearing that up

**Comment by JarodMica** [comment]
> ah yup that's exactly why, im trying to run it on gpu, thanks for clearing that up

Gotcha, a common thing that happens is something went wrong with the torch installation, so you can ```pip uninstall torch``` and then run installation again as it's not seeing that CUDA is available.

**Comment by HonestyLied** [comment]
thank you! reinstalling torch and reseting the infer file fixed it! thanks!

**Comment by JarodMica** [comment]
Awesome, glad it's working so I'll be closing this issue now :)!
